### ISSUE TITLE
Patch shebangs to specify python 2 interpreter.

### ISSUE THREAD

**Issue by jerry73204** [planetsumo/sumo#10]
I have Python 3 installed by default on Arch Linux. However, most of .{py,pyw} files has shebangs like `#!/usr/bin/env python`,`#!/usr/bin/python`, or missing. Executing these files would invoke the Python 3 interpreter, causing it to fail. I have to manually patch them to `#!/usr/bin/env python2` to fix them up. It would be fine if it could be resolved in upstream. Here is the script copied from [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sumo) on [AUR](https://aur.archlinux.org/packages/sumo/).
```sh
find . -iname \*.py  -exec sed -i 's/#!\/usr\/bin\/env python/#!\/usr\/bin\/env python2/' {} \;
find . -iname \*.pyw -exec sed -i 's/#!\/usr\/bin\/env python/#!\/usr\/bin\/env python2/' {} \;
find . -iname \*.py  -exec sed -i 's/#!\/usr\/bin\/python/#!\/usr\/bin\/python2/' {} \;

for f in $(find . -iname \*.py)                                                                                                          
do                                                                                                                                       
    if [ -z "$(grep -l '^#!/.*python' "$f")" ]; then                                                                                     
        sed -i "1i #!/bin/env python2" $f                                                                                                
    fi                                                                                                                                   
done   
```

**Comment by sumotest** [comment]
The sumo tools are intended to work with python3 and python2. Please be more specific about which files lack python3 compatibility.

**Comment by jerry73204** [comment]
I didn't checked the Python 3 compatibility. Sorry for that.
Indeed, IMHO, dual compatibility on both Python 2 &3 is not a good idea. There are several reasons we should avoid it.
1. Dual compatibility implies dual dependencies. This script `tools/assign/Assignment.py` imports a `table` module, which does not in standard library. I have to install the `tables` for both python{2,3}.
2. The standard library of Py {2,3} are not fully compatible. For instance, `cPickle` is missing on Py3 in `tools/contributed/sumopy/agilepy/lib_wx/wxmisc.py`, and pickle should be loaded/dumped in bytes interface rather than str on Py 3.
3. Though syntax could be the same on Python {2,3}, the behavior could differ. `print(1, 2)` results in space separated output `1 2` on Py 3, but it prints a tuple on Py 2 instead. Also, `range` is another case. `range` creates a generator on Py 3 while `ranges` creates a list on Py 2. The memory consumption can be dramatically enormous on Py 2 if the range is large.

It's fine to get close to either Py 2 or 3, but dual compatibility may lead to troubles.

**Comment by sumotest** [comment]
I do not agree with the first point. You only need to install for the version you are actively using. Only developers need to have both. The second one should be fixed but it is an external contribution anyway. For print we are encouraging the use of `from __future__ import print_function` and yes there are sometimes subtle differences also concerning (integer) division but we decided to accept that, because the alternative is to force everyone to install python2 when it is simply not necessary.

**Comment by behrisch** [comment]
We will probably not change our approach to python 2/3 compatibility anytime soon.
