### ISSUE TITLE
User defined controller for individual vehicle

### ISSUE THREAD

**Issue by bmmi** [planetsumo/sumo#3]
Hi there,

Is it possible to specify a _customized_ controller for _each_ vehicle in the simulation? (not the _predefined_ car-following, lane-changing, collision-avoidance controllers/dynamics)

Thanks.

**Comment by planetsumo** [comment]
Yes, all vehicles may use different models either implement your own using http://sumo.dlr.de/wiki/Developer/How_To/Car-Following_Model or remote control the using TraCI http://sumo.dlr.de/wiki/TraCI
