### ISSUE TITLE
pc_typemap.h missing from mirror

### ISSUE THREAD

**Issue by Robadob** [planetsumo/sumo#4]
Just cloned the git repo, followed [this](http://sumo.dlr.de/wiki/Installing/Windows_Build) guide to build x86 under VS2013. Found that `polyconvert` fails to build because [`pc_typemap.h`](http://www.sumo.dlr.de/daily/doxygen/da/d7d/pc__typemap_8h.html) is missing. I manually added back the linked file, and build worked as expected.

---------------------

Unrelated issue I noticed, the [`fox-1.6.52_64vc12.zip`](https://sourceforge.net/projects/sumo/files/dependencies/) dependency download, appears to be corrupt. It's visibly missing a large number of files present in the x86 copy (I haven't attempted a build, perhaps they're unnecessary), and on extracting with 7zip I received a  'data-error' regarding `\doc\screenshots\vorhour2_small.jpg`. Windows explorer outright refuses to open the zip calling it corrupt.

**Comment by behrisch** [comment]
The first one is probably due to a slightly corrupted python
installation, please check here:
http://stackoverflow.com/questions/2640971/windows-is-not-passing-command-line-arguments-to-python-programs-executed-from-t.
I updated the windows build page as well.
I keep the ticket open for the second issue.

**Comment by Robadob** [comment]
That would make sense, I don't believe `.py` files were previously tied to any software (installed via anaconda), I created the association manually when windows asked.

I managed to build fox x64 myself, so the latter point hasn't held me back.

Thanks

**Comment by behrisch** [comment]
Moved to http://sumo.dlr.de/trac.wsgi/ticket/3013
