### ISSUE TITLE
Trying to make my own executable

### ISSUE THREAD

**Issue by jaehy1** [planetsumo/sumo#6]
Hello,

I am so sorry if this seems like a unproductive post, however I was wondering if anyone can help me. I am trying to run my own executable version of emissionsDrivingCycle (I know there is already one available) for my own needs. The problem is when I go into linux and into the directory of sumo/src/tools, I find that there is a Makefile.am, but no configure.ac. I am unfamiliar with how to use a Makefile.am, but I have used a Makefile before. I apologize for the inconvenience, but please let me know if anyone is able to answer this question. (I am just trying to make my own executable of emissionsDrivingCycle)

Thank you in advance,
Jay

**Comment by behrisch** [comment]
You need to run the main configure in the sumo dir which will build all Makefiles in subdirs. If you are using a fresh clone make sure to run autoreconf -i first (or make -f Makefile.cvs).
