### ISSUE TITLE
Where are the examples directory?

### ISSUE THREAD

**Issue by peheje** [planetsumo/sumo#7]
"To get started with SUMO, take a look at the examples directory". Where is it? Can't find it either on: https://svn.code.sf.net/p/sumo/code/trunk/sumo/

**Comment by AuspeXeu** [comment]
You looking for the examples mentioned in the tutorials? They are [here](https://github.com/planetsumo/sumo/tree/master/sumo/tests/complex/tutorial)

**Comment by peheje** [comment]
Thanks!
