### ISSUE TITLE
getAccumulatedWaitingTime from traci not available from python

### ISSUE THREAD

**Issue by peheje** [planetsumo/sumo#8]
When I try to call getAccumulatedWaitingTime from traci.vehicle from Python, I get the following error:
"
File "...Traci_2_cross_env.py", line 158, in _step
    acc_wait = traci.vehicle.getAccumulatedWaitingTime(cars_on_in_inductor[0])
AttributeError: 'VehicleDomain' object has no attribute 'getAccumulatedWaitingTime'
"
SUMO Version 0.30.0

The function is documented here:
http://www.sumo.dlr.de/daily/pydoc/traci._vehicle.html

Getting the acceleration works fine as shown here: https://www.dropbox.com/s/yqqfma01r858fxd/Screenshot%202017-09-14%2015.55.34.png?dl=0

**Comment by behrisch** [comment]
The function has been added to the python client after the release of 0.30.0. The docs you are referring to relate to the nightly build.
