### ISSUE TITLE
Can sumo-gui support high-resolution(4k) screen?

### ISSUE THREAD

**Issue by JINKEHE** [planetsumo/sumo#9]
Hi,

SUMO-gui user interface works fine under the resolution of 1920x1080 but everything is so small under the resolution of 4096x2160. Any method to solve this?

**Comment by behrisch** [comment]
Most of the drawn elements like cars and streets can be scaled up using the settings or by just zooming in but I think the buttons and menus are bitmap based and do not scale well and we do not have any code for trying to do so. You may try with some buttons (in the code) to give them larger size and report your findings, maybe we can find a fast and simple solution.

**Comment by behrisch** [comment]
I moved this to the main issue tracker
